version: "3.9"

secrets:
  postgres_password:
    external: true
  dragonfly_password:
    external: true
  hanko_secret_key:
    external: true
  oauth2_proxy_client_secret:
    external: true

networks:
  web:
    driver: overlay
    attachable: true
  internal:
    driver: overlay

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: razcloud
      POSTGRES_USER: razcloud
      # Use Docker secret file
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    # Dragonfly has no *_FILE env; read the secret file and pass as arg
    command: >
      sh -c 'dragonfly
             --requirepass "$$(cat /run/secrets/dragonfly_password)"
             --bind 0.0.0.0:6379'
    secrets:
      - dragonfly_password
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  # DB broker that creates per-app DBs and returns URIs
  database-broker:
    image: ghcr.io/razzie-cloud/database-broker:1.0.2
    depends_on:
      - postgres
      - dragonfly
    secrets:
      - postgres_password
      - dragonfly_password
    environment:
      POSTGRES_URI: postgresql://razcloud@postgres:5432/razcloud
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      DRAGONFLY_URI: redis://dragonfly:6379
      DRAGONFLY_PASSWORD_FILE: /run/secrets/dragonfly_password
    networks:
      - internal
    deploy:
      restart_policy:
        condition: on-failure

  hanko:
    image: ghcr.io/razzie-cloud/hanko:latest
    networks:
      - internal
      - web
    depends_on:
      - database-broker
    secrets:
      - hanko_secret_key
    deploy:
      labels:
        # Hanko public API & UI
        caddy: auth.razzie.cloud
        caddy.reverse_proxy: "{{upstreams 8000}}"
      restart_policy:
        condition: on-failure

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.13.0
    networks:
      - web
      - internal
    depends_on:
      - hanko
    secrets:
      - oauth2_proxy_client_secret
    environment:
      # Use Hanko as an OIDC provider (you must configure the client in Hanko)
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://auth.razzie.cloud
      OAUTH2_PROXY_CLIENT_ID: hanko-oauth-client
      OAUTH2_PROXY_CLIENT_SECRET_FILE: /run/secrets/oauth2_proxy_client_secret
      OAUTH2_PROXY_REDIRECT_URL: https://oauth2.razzie.cloud/oauth2/callback
      # Generic oauth2-proxy bits
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      # For Caddy forward_auth integration :contentReference[oaicite:0]{index=0}
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_UPSTREAMS: "static://202"
    deploy:
      labels:
        # Expose oauth2-proxy itself (for /oauth2/* endpoints)
        caddy: oauth2.razzie.cloud
        caddy.reverse_proxy: "{{upstreams 4180}}"
      restart_policy:
        condition: on-failure

  # Whoami demo app, fully hidden behind auth wall
  whoami:
    image: traefik/whoami
    networks:
      - web
    deploy:
      labels:
        caddy: whoami.razzie.cloud
        caddy.reverse_proxy: "{{upstreams 80}}"
        # Apply auth snippet defined on the Caddy service
        caddy.import: oauth2_forward_auth
      restart_policy:
        condition: on-failure

  # Caddy + caddy-docker-proxy, 80/443 open to the world
  caddy-docker-proxy:
    image: lucaslorentz/caddy-docker-proxy:2.8-alpine
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CADDY_INGRESS_NETWORKS: "${STACK_NAME}_web"
      # CADDY_EMAIL: "system@razzie.cloud"   # optionally set ACME email
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        # Define a reusable forward_auth snippet to oauth2-proxy :contentReference[oaicite:1]{index=1}
        caddy: (oauth2_forward_auth)
        caddy.forward_auth: oauth2-proxy:4180
        caddy.forward_auth.uri: /oauth2/auth
